### ISSUE TITLE
🚀 Feature:  Implement Backblaze S3 Adapter

### ISSUE THREAD

**Issue by Swinkid** [utopia-php/storage#25]
### 🔖 Feature description

I would like support to be added for Backblaze B2. They have an S3 compatible API that I've already wrote an adaptor for that I haven't yet pushed.

Their API Can be found at: https://www.backblaze.com/b2/docs/s3_compatible_api.html

### 🎤 Pitch

In my use-case I'd like to be able to store files on Backblaze instead of DO Spaces or AWS S3. It seems like a quick win to add support for it by adding an adapter that extends from the AWS A3 object.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
We plan to work on this in the next few weeks.

**Comment by metadaddy** [comment]
Isn't this done? I see the code in the `main` branch.
