### ISSUE TITLE
List of regions in Backblaze 

### ISSUE THREAD

**Issue by metadaddy** [utopia-php/storage#48]
### 👟 Reproduction steps

When I look at the list of regions in the Backblaze adapter code, it is wrong. I'll submit a PR to fix it.

### 👍 Expected behavior

It should list the correct regions:

```php
    const US_WEST_000 = 'us-west-000';
    const US_WEST_001 = 'us-west-001';
    const US_WEST_002 = 'us-west-002';
    const US_WEST_004 = 'us-west-004';
    const EU_CENTRAL_003 = 'eu-central-003';
```

### 👎 Actual Behavior

It actually has an incorrect list of B2 regions:

```
    const US_WEST_001 = 'us-west-001';
    const US_WEST_002 = 'us-west-002';
    const US_WEST_003 = 'us-west-003';
    const US_WEST_004 = 'us-west-004';
    const EU_CENTRAL_001 = 'eu-central-001';
    const EU_CENTRAL_002 = 'eu-central-002';
    const EU_CENTRAL_003 = 'eu-central-003';
    const EU_CENTRAL_004 = 'eu-central-004';
```

### 🎲 Utopia Storage Version

Version 0.5.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Vanilla

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Fixed #49
