### ISSUE TITLE
🚀 Feature: Looking to add support for cloudflare r2

### ISSUE THREAD

**Issue by linny006** [utopia-php/storage#52]
### 🔖 Feature description

Looking to add support for cloudflare r2

### 🎤 Pitch

Looking to add support for cloudflare r2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by doublevcodes** [comment]
Hello, I'd like to tackle this as I mentioned in appwrite/appwrite#3352. Could I please be assigned?

**Comment by stnguyen90** [comment]
Let's use https://github.com/appwrite/appwrite/issues/3352 to track this.
