### ISSUE TITLE
🚀 Feature: Adding S3 adapter for Yandex Object Storage

### ISSUE THREAD

**Issue by polbuhanky** [utopia-php/storage#86]
### 🔖 Feature description

Adding S3 adapter for Yandex Object Storage. 
You can check information about storage by this link: https://cloud.yandex.com/en/services/storage

### 🎤 Pitch

Now appwrite supports 5 adapters (AWS S3, Digital Ocean Spaces, Backblaze, Akamai Object Storage, and Wasabi), but all of them are not suitable for the CIS market.  I am trying to popularize appwrite in Russia and other close countries, but working with appwrite is difficult without storage. Adding this adapter will allow the appwrite platform to expand in new territories! Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by hydromoll** [comment]
I wanna do it

**Comment by polbuhanky** [comment]
@stnguyen90 , @hydromoll added his solution to utopia-php. Can you check it out? When will other users be able to start using this solution?
